/**
 * Thomas pics — portfolio browser.
 *
 * Every collection and photo comes from `window.PHOTO_LIBRARY` (regenerated by
 * `scripts/build_photo_data.py`). The tree ships the camera originals, so
 * `thumb` and `large` name the same full-resolution file: the grid, the
 * lightbox and the hero collage all show it at full quality, never a
 * downscaled or re-encoded copy.
 *
 * Ratings are stored per visitor in localStorage. There is no invented
 * aggregate score: the panel only ever reports the visitor's own rating.
 */

(function () {
  const LIBRARY = window.PHOTO_LIBRARY || null;
  const DERIVED_FALLBACK_COPY = {
    nature: "山野、海岸、湖泊与季节光线构成的自然影像档案。",
    city: "街道、建筑、灯光与人群移动之间的城市节奏。",
    people: "人物、现场与真实关系共同组成的纪实肖像。",
    events: "活动、会议与集体现场中的秩序、表情和瞬间。",
  };

  const galleryNode = document.querySelector("#portfolioGallery");

  function showLibraryMissing() {
    if (galleryNode) {
      galleryNode.innerHTML = `
        <p class="library-missing">
          图库数据未加载。请先运行 <code>python scripts/build_photo_data.py --write</code> 重新生成
          <code>photo-data.js</code>。
        </p>
      `;
    }
  }

  if (!LIBRARY?.topics) {
    showLibraryMissing();
    return;
  }

  let categoryInfo = {};
  let projects = [];
  let photos = [];

  // Both fields name the same original; the fallback only guards against a
  // hand-edited data file where one of them went missing.
  function gridSource(photo) {
    return photo?.thumb || photo?.large || "";
  }

  function largeSource(photo) {
    return photo?.large || photo?.thumb || "";
  }

  function hydratePortfolioFromPhotoLibrary() {
    const topics = LIBRARY.topics;
    const libraryProjects = LIBRARY.projects;

    Object.entries(topics).forEach(([key, topic]) => {
      if (!topic.photos?.length) return;

      const cover = topic.photos[0];
      categoryInfo[key] = {
        label: topic.label,
        title: topic.title || topic.label,
        intro: topic.intro || DERIVED_FALLBACK_COPY[key] || `${topic.label}分类作品，共 ${topic.count} 张。`,
        hero: largeSource(cover),
      };

      projects.push({
        id: `topic-${key}`,
        title: topic.title || topic.label,
        category: key,
        location: "本地图库",
        count: `${topic.count} 张`,
        description: categoryInfo[key].intro,
        cover: gridSource(cover),
      });

      photos.push(
        ...topic.photos.map((photo) => ({
          ...photo,
          category: key,
          title: photo.title || photo.filename,
          categoryLabel: topic.label,
        }))
      );
    });

    if (libraryProjects) {
      projects = Object.values(libraryProjects)
        .filter((project) => project.photos?.length)
        .map((project) => {
          // Match the cover by photo id so replacing or re-encoding a file
          // cannot silently point the tile at a different photo.
          const coverPhoto =
            project.photos.find((photo) => photo.id === project.coverId) || project.photos[0];
          return {
            id: project.id || project.key,
            title: project.title || project.label,
            category: project.id || project.key,
            location: project.chapters?.length ? project.chapters.join(" / ") : "本地项目",
            count: `${project.count} 张`,
            description: project.intro || `${project.label || project.title}，共 ${project.count} 张作品。`,
            coverId: coverPhoto.id,
            cover: gridSource(coverPhoto),
            photos: project.photos.map((photo) => ({
              ...photo,
              category: project.id || project.key,
              categoryLabel: project.label || project.title,
              title: photo.title || photo.filename,
            })),
            groupLabel: "沉浸式作品集",
          };
        });
    }
  }

  hydratePortfolioFromPhotoLibrary();

  const params = new URLSearchParams(window.location.search);
  const requestedCategory = params.get("category");
  const requestedProject = params.get("project");
  const selectedProject = projects.find((project) => project.id === requestedProject);
  const requestedKey = selectedProject ? selectedProject.category : requestedCategory || Object.keys(categoryInfo)[0];
  const activeKey = categoryInfo[requestedKey] ? requestedKey : Object.keys(categoryInfo)[0];
  const activeCategory = categoryInfo[activeKey];

  const hero = document.querySelector("#portfolioHero");
  const eyebrow = document.querySelector("#portfolioEyebrow");
  const title = document.querySelector("#portfolioTitle");
  const intro = document.querySelector("#portfolioIntro");
  const tabs = document.querySelector("#topicTabs");
  const summary = document.querySelector("#portfolioSummary");
  const gallery = document.querySelector("#portfolioGallery");
  const lightbox = document.querySelector("#portfolioLightbox");
  const imageStage = document.querySelector("#portfolioImageStage");
  const lightboxImage = document.querySelector("#portfolioLightboxImage");
  const lightboxTitle = document.querySelector("#portfolioLightboxTitle");
  const lightboxMeta = document.querySelector("#portfolioLightboxMeta");
  const lightboxCounter = document.querySelector("#portfolioLightboxCounter");
  const ratingPanel = document.querySelector("#portfolioRating");
  const ratingAverage = document.querySelector("#portfolioRatingAverage");
  const ratingSummary = document.querySelector("#portfolioRatingSummary");
  const fullscreenButton = document.querySelector("#portfolioFullscreen");
  const zoomButton = document.querySelector("#portfolioZoom");
  let visiblePhotos = [];
  let activeLightboxIndex = 0;
  let lightboxRenderToken = 0;
  let wheelLocked = false;
  let zoomed = false;
  let zoomOrigin = { x: 50, y: 50 };
  let zoomOffset = { x: 0, y: 0 };
  let dragState = null;

  function shufflePhotos(items) {
    const shuffled = [...items];
    for (let index = shuffled.length - 1; index > 0; index -= 1) {
      const nextIndex = Math.floor(Math.random() * (index + 1));
      [shuffled[index], shuffled[nextIndex]] = [shuffled[nextIndex], shuffled[index]];
    }
    return shuffled;
  }

  function formatPhotoMeta(photo) {
    const values = [
      photo.chapter,
      photo.categoryLabel || categoryInfo[photo.category]?.label,
      photo.time,
      photo.camera,
      [photo.focalLength, photo.aperture, photo.shutter, photo.iso].filter(Boolean).join(" · "),
      photo.location ? `地点 ${photo.location}` : "",
    ].filter(Boolean);
    return values.join(" / ");
  }

  function getPhotoStorageKey(photo) {
    return `thomas-pics-rating:${photo.id || photo.master || photo.title}`;
  }

  /** Only the visitor's own rating is shown — no fabricated community score. */
  function getStoredRating(photo) {
    const value = Number(localStorage.getItem(getPhotoStorageKey(photo)));
    return Number.isFinite(value) ? value : 0;
  }

  function setPhotoRating(photo, rating) {
    localStorage.setItem(getPhotoStorageKey(photo), rating.toString());
  }

  function renderRating(photo, changedRating = 0) {
    const userRating = getStoredRating(photo);
    ratingPanel.classList.remove("rating-just-changed");
    ratingPanel.querySelectorAll("button").forEach((button) => {
      const value = Number(button.dataset.rating);
      button.classList.remove("just-rated");
      button.classList.toggle("active", value <= userRating);
      button.setAttribute("aria-checked", value === userRating ? "true" : "false");
      button.setAttribute("role", "radio");
    });

    ratingAverage.textContent = userRating ? `${userRating}.0` : "--";
    ratingSummary.textContent = userRating ? "你在本机给出的评分" : "点星星打个分";

    if (changedRating) {
      void ratingPanel.offsetWidth;
      ratingPanel.classList.add("rating-just-changed");
      ratingPanel.querySelectorAll("button").forEach((button) => {
        const value = Number(button.dataset.rating);
        if (value <= changedRating) {
          button.classList.add("just-rated");
        }
      });
    }
  }

  function updateZoom() {
    lightbox.classList.toggle("is-zoomed", zoomed);
    zoomButton.classList.toggle("active", zoomed);
    zoomButton.setAttribute("aria-pressed", zoomed ? "true" : "false");
    lightboxImage.style.transformOrigin = `${zoomOrigin.x}% ${zoomOrigin.y}%`;
    lightboxImage.style.transform = zoomed
      ? `translate3d(${zoomOffset.x}px, ${zoomOffset.y}px, 0) scale(2.15)`
      : "";
  }

  function resetZoom() {
    zoomed = false;
    zoomOrigin = { x: 50, y: 50 };
    zoomOffset = { x: 0, y: 0 };
    dragState = null;
    updateZoom();
  }

  function setZoomFromEvent(event) {
    const bounds = imageStage.getBoundingClientRect();
    const x = ((event.clientX - bounds.left) / bounds.width) * 100;
    const y = ((event.clientY - bounds.top) / bounds.height) * 100;
    zoomOrigin = {
      x: Math.min(100, Math.max(0, x)),
      y: Math.min(100, Math.max(0, y)),
    };
    zoomOffset = { x: 0, y: 0 };
  }

  function toggleZoom(event) {
    if (!zoomed && typeof event?.clientX === "number") {
      setZoomFromEvent(event);
    }
    zoomed = !zoomed;
    if (!zoomed) {
      zoomOffset = { x: 0, y: 0 };
    }
    updateZoom();
  }

  function openLightboxAt(index) {
    if (!visiblePhotos.length) return;
    lightboxRenderToken += 1;
    const renderToken = lightboxRenderToken;
    activeLightboxIndex = (index + visiblePhotos.length) % visiblePhotos.length;
    const photo = visiblePhotos[activeLightboxIndex];
    if (!photo) return;

    resetZoom();
    lightboxImage.classList.remove("is-loaded");
    lightboxImage.onload = () => {
      if (renderToken !== lightboxRenderToken) return;
      lightboxImage.classList.add("is-loaded");
    };
    lightboxImage.decoding = "async";
    lightboxImage.src = largeSource(photo);
    lightboxImage.alt = photo.title;
    if (lightboxImage.complete) {
      lightboxImage.onload();
    }
    lightboxTitle.textContent = photo.title;
    lightboxMeta.textContent = formatPhotoMeta(photo);
    lightboxCounter.textContent = `${activeLightboxIndex + 1} / ${visiblePhotos.length}`;
    renderRating(photo);

    if (!lightbox.open) {
      lightbox.showModal();
    }
  }

  function changeLightboxPhoto(step) {
    openLightboxAt(activeLightboxIndex + step);
  }

  function setFullscreenState(active) {
    lightbox.classList.toggle("is-fullscreen", active);
    fullscreenButton.classList.toggle("active", active);
    fullscreenButton.setAttribute("aria-pressed", active ? "true" : "false");
    fullscreenButton.title = active ? "退出全屏" : "全屏观看";
  }

  async function exitFullscreenView() {
    if (document.fullscreenElement) {
      await document.exitFullscreen();
      return;
    }
    setFullscreenState(false);
  }

  async function enterFullscreenView() {
    try {
      if (lightbox.requestFullscreen) {
        await lightbox.requestFullscreen();
        setFullscreenState(document.fullscreenElement === lightbox);
        if (document.fullscreenElement === lightbox) return;
      }
    } catch (error) {
      console.warn("Fullscreen request was not completed. Using in-page fullscreen instead.", error);
    }

    setFullscreenState(true);
  }

  function getProjectGroup(project) {
    return { key: project.id, label: project.groupLabel || "沉浸式作品集" };
  }

  function renderTabs() {
    if (selectedProject) {
      tabs.innerHTML = projects
        .filter((project) => project.id === selectedProject.id || !project.id.startsWith("topic-"))
        .map((project) => {
          const active = project.id === selectedProject.id ? "active" : "";
          return `<a class="${active}" href="portfolio.html?project=${encodeURIComponent(project.id)}">${project.title}</a>`;
        })
        .join("");
      return;
    }

    tabs.innerHTML = Object.entries(categoryInfo)
      .map(([key, item]) => {
        const active = key === activeKey ? "active" : "";
        return `<a class="${active}" href="portfolio.html?category=${encodeURIComponent(key)}">${item.label}</a>`;
      })
      .join("");
  }

  function getVisiblePhotos() {
    if (!selectedProject) {
      return shufflePhotos(photos.filter((photo) => photo.category === activeKey));
    }
    return shufflePhotos(selectedProject.photos || []);
  }

  function renderPage() {
    visiblePhotos = getVisiblePhotos();
    const heroPhoto = selectedProject
      ? visiblePhotos.find((photo) => photo.id === selectedProject.coverId) || visiblePhotos[0]
      : visiblePhotos[Math.floor(Math.random() * visiblePhotos.length)];
    const heroImage = heroPhoto ? largeSource(heroPhoto) : activeCategory.hero;
    const projectGroup = selectedProject ? getProjectGroup(selectedProject) : null;
    hero.style.setProperty("--portfolio-hero-image", `url("${heroImage}")`);
    eyebrow.textContent = selectedProject ? `Selected Project · ${projectGroup.label}` : "Topic Collection";
    title.textContent = selectedProject ? selectedProject.title : activeCategory.title;
    intro.textContent = selectedProject ? selectedProject.description : activeCategory.intro;

    summary.innerHTML = selectedProject
      ? `
        <span>${projectGroup.label}</span>
        <strong>${selectedProject.location}</strong>
        <em>${selectedProject.count}</em>
      `
      : `
        <span>${activeCategory.label}</span>
        <strong>${visiblePhotos.length} 张作品</strong>
        <em>按分类整理</em>
      `;

    gallery.innerHTML = visiblePhotos
      .map(
        (photo, index) => `
          <button class="masonry-photo ${photo.ratio || "standard"}" type="button" data-index="${index}">
            <img src="${gridSource(photo)}" alt="${photo.title}" loading="lazy" decoding="async">
          </button>
        `
      )
      .join("");
  }

  renderTabs();
  renderPage();

  const yearNode = document.querySelector("#year");
  if (yearNode) yearNode.textContent = new Date().getFullYear();

  gallery.addEventListener("click", (event) => {
    const card = event.target.closest(".masonry-photo");
    if (!card) return;

    openLightboxAt(Number(card.dataset.index));
  });

  document.querySelector(".close-lightbox").addEventListener("click", () => lightbox.close());

  fullscreenButton.addEventListener("click", async () => {
    if (document.fullscreenElement === lightbox || lightbox.classList.contains("is-fullscreen")) {
      await exitFullscreenView();
      return;
    }

    await enterFullscreenView();
  });

  zoomButton.addEventListener("click", () => toggleZoom());

  imageStage.addEventListener("dblclick", (event) => {
    event.preventDefault();
    toggleZoom(event);
  });

  imageStage.addEventListener("pointerdown", (event) => {
    if (!zoomed || event.button !== 0) return;
    event.preventDefault();
    dragState = {
      pointerId: event.pointerId,
      startX: event.clientX,
      startY: event.clientY,
      offsetX: zoomOffset.x,
      offsetY: zoomOffset.y,
    };
    imageStage.setPointerCapture(event.pointerId);
  });

  imageStage.addEventListener("pointermove", (event) => {
    if (!dragState || event.pointerId !== dragState.pointerId) return;
    zoomOffset = {
      x: dragState.offsetX + event.clientX - dragState.startX,
      y: dragState.offsetY + event.clientY - dragState.startY,
    };
    updateZoom();
  });

  function stopDragging(event) {
    if (!dragState || event.pointerId !== dragState.pointerId) return;
    dragState = null;
    if (imageStage.hasPointerCapture(event.pointerId)) {
      imageStage.releasePointerCapture(event.pointerId);
    }
  }

  imageStage.addEventListener("pointerup", stopDragging);
  imageStage.addEventListener("pointercancel", stopDragging);

  document.addEventListener("fullscreenchange", () => {
    setFullscreenState(document.fullscreenElement === lightbox);
  });

  lightbox.addEventListener("close", () => {
    resetZoom();
    setFullscreenState(false);
    if (document.fullscreenElement === lightbox) {
      document.exitFullscreen().catch(() => {});
    }
  });

  ratingPanel.addEventListener("click", (event) => {
    const button = event.target.closest("[data-rating]");
    if (!button) return;
    const photo = visiblePhotos[activeLightboxIndex];
    if (!photo) return;
    const rating = Number(button.dataset.rating);
    setPhotoRating(photo, rating);
    renderRating(photo, rating);
  });

  lightbox.addEventListener(
    "wheel",
    (event) => {
      if (!lightbox.open || wheelLocked) return;
      event.preventDefault();
      if (zoomed) return;

      const direction = event.deltaY > 0 ? 1 : -1;
      wheelLocked = true;
      changeLightboxPhoto(direction);
      window.setTimeout(() => {
        wheelLocked = false;
      }, 280);
    },
    { passive: false }
  );

  document.addEventListener("keydown", (event) => {
    if (event.key === "Escape" && lightbox.open) {
      lightbox.close();
    }
    if (!lightbox.open) return;
    if (event.key === "ArrowRight" || event.key === "ArrowDown") {
      changeLightboxPhoto(1);
    }
    if (event.key === "ArrowLeft" || event.key === "ArrowUp") {
      changeLightboxPhoto(-1);
    }
  });

  // Touch devices have no wheel: swipe to move between photos.
  let touchStartX = null;
  imageStage.addEventListener(
    "touchstart",
    (event) => {
      if (zoomed) return;
      touchStartX = event.changedTouches[0]?.clientX ?? null;
    },
    { passive: true }
  );
  imageStage.addEventListener(
    "touchend",
    (event) => {
      if (zoomed || touchStartX === null) return;
      const delta = (event.changedTouches[0]?.clientX ?? touchStartX) - touchStartX;
      touchStartX = null;
      if (Math.abs(delta) < 45) return;
      changeLightboxPhoto(delta < 0 ? 1 : -1);
    },
    { passive: true }
  );
})();
