/**
 * Thomas pics — homepage behaviour.
 *
 * All content comes from `window.PHOTO_LIBRARY`, which is generated by
 * `scripts/build_photo_data.py` from the JPEGs under `assets/opt/`.
 * There is deliberately no sample/placeholder content in this file: if the
 * library is missing, the page says so instead of inventing projects.
 */

const PLACEHOLDER_COPY = {
  nature: "山野、海岸、湖泊与季节光线构成的自然影像档案。",
  city: "街道、建筑、灯光与人群移动之间的城市节奏。",
  people: "人物、现场与真实关系共同组成的纪实肖像。",
  events: "活动、会议与集体现场中的秩序、表情和瞬间。",
};

const PROJECT_GROUP_LABEL = "沉浸式作品集";

const gallery = document.querySelector("#gallery");
const filterBar = document.querySelector(".filter-bar");
let filterButtons = [...document.querySelectorAll(".filter-button")];
const collectionGrid = document.querySelector(".collection-grid");
const navLinks = [...document.querySelectorAll(".nav-links a[href^='#']")];
const lightbox = document.querySelector("#lightbox");
const lightboxImage = document.querySelector("#lightboxImage");
const lightboxTitle = document.querySelector("#lightboxTitle");
const lightboxMeta = document.querySelector("#lightboxMeta");
const lightboxStory = document.querySelector("#lightboxStory");
const projectForm = document.querySelector("#projectForm");
const ideaToast = document.querySelector("#ideaToast");
const heroImages = [...document.querySelectorAll(".collage-image")];

/** 唯一维护点：邮箱与微信同时用于联系区块与表单提交失败时的兜底提示。 */
const CONTACT_EMAIL = "605710591@qq.com";
const CONTACT_WECHAT = "chengyu_95";

// 首页拼贴的预制图组，来自 hero-sets.js（4 组 × 6 张 960px 小图）。
// 为空时退回原片，而且不做轮播 —— 见 initHeroAutoGallery 的说明。
let heroSets = [];
let portfolioProjects = [];
let visibleWorks = [];
let activeIndex = 0;

function getPhotoLibrary() {
  return window.PHOTO_LIBRARY || null;
}

/**
 * The deployed tree ships the camera originals themselves, so `thumb` and
 * `large` name the same file: whatever is picked here is the full-resolution
 * JPEG, byte-for-byte as exported.
 */
function gridSource(photo) {
  return photo?.thumb || photo?.large || "";
}

/** The lightbox shows that same original; there is no smaller variant to fall back to. */
function largeSource(photo) {
  return photo?.large || photo?.thumb || "";
}

function pickRandomPhoto(items) {
  if (!items?.length) return null;
  return items[Math.floor(Math.random() * items.length)];
}

function topicToWork(topic) {
  const cover = pickRandomPhoto(topic.photos);
  return {
    id: `topic-${topic.key}`,
    title: topic.title || topic.label,
    categoryLabel: topic.label,
    location: "本地图库",
    count: `${topic.count} 张`,
    thumb: gridSource(cover),
    large: largeSource(cover),
    alt: cover?.title || topic.title || topic.label,
    story: topic.intro || PLACEHOLDER_COPY[topic.key] || `${topic.label}，共 ${topic.count} 张作品。`,
  };
}

/** Cover photos are matched by id, so replacing a file cannot break the pairing. */
function findCover(photos, coverId) {
  if (!photos?.length) return null;
  return photos.find((photo) => photo.id === coverId) || photos[0];
}

function projectToWork(project) {
  const cover = findCover(project.photos, project.coverId);
  return {
    id: project.id || project.key,
    title: project.title || project.label,
    categoryLabel: project.label || project.title,
    groupLabel: PROJECT_GROUP_LABEL,
    location: project.chapters?.length ? project.chapters.join(" / ") : "本地项目",
    count: `${project.count} 张`,
    thumb: gridSource(cover),
    large: largeSource(cover),
    alt: cover?.title || project.title || project.label,
    story: project.intro || `${project.label || project.title}，共 ${project.count} 张作品。`,
  };
}

function rebuildWorkFilters(projectList) {
  if (!filterBar || !projectList?.length) return;
  filterBar.innerHTML = [
    `<button class="filter-button active" type="button" data-filter="all">全部</button>`,
    ...projectList.map(
      (project) =>
        `<button class="filter-button" type="button" data-filter="${project.id || project.key}">${
          project.label || project.title
        }</button>`
    ),
  ].join("");
  filterButtons = [...document.querySelectorAll(".filter-button")];
}

function setMetric(node, value) {
  if (!node) return;
  node.dataset.countTarget = String(value);
  node.textContent = String(value);
}

function renderLibraryMissing() {
  if (gallery) {
    gallery.innerHTML = `
      <p class="library-missing">
        图库数据未加载。请先运行 <code>python scripts/build_photo_data.py --write</code> 重新生成
        <code>photo-data.js</code>。
      </p>
    `;
  }
  const metrics = document.querySelectorAll(".metric[data-count-target]");
  metrics.forEach((metric) => {
    metric.dataset.countTarget = "0";
    metric.textContent = "0";
  });
}

function hydrateSiteFromPhotoLibrary() {
  const library = getPhotoLibrary();
  const topics = library?.topics;
  if (!topics) {
    renderLibraryMissing();
    return false;
  }

  const topicList = Object.values(topics).filter((topic) => topic.photos?.length);
  const projectList = Object.values(library.projects || {}).filter((project) => project.photos?.length);
  if (!topicList.length && !projectList.length) {
    renderLibraryMissing();
    return false;
  }

  // 首页拼贴：优先用 hero-sets.js 的预制小图。
  //
  // 拼贴每格最多显示 456×257 CSS px，而原片是 6000×4000（24 MP）——像素多出约 51 倍。
  // 用原片做轮播等于每 2 秒下载约 45 MB、解码约 576 MB 位图，这是首页卡顿的根源。
  // 小图由 scripts/build_hero_sets.py 生成，只服务这个装饰性拼贴；
  // 作品集、灯箱、专题页读的仍是 photo-data.js 里的原片，互不影响。
  heroSets = Array.isArray(window.HERO_SETS)
    ? window.HERO_SETS.filter((set) => set?.images?.length >= heroImages.length)
    : [];

  let heroSources;
  let heroAlts;

  if (heroSets.length) {
    heroSources = heroSets[0].images.map((item) => item.src);
    heroAlts = heroSets[0].images.map((item) => item.alt || "");
  } else {
    // 没有 hero-sets.js：只能用原片，但只静态显示一组，不轮播。
    const heroSource = topics.nature?.photos?.length
      ? topics.nature.photos
      : topicList.flatMap((topic) => topic.photos);
    const picks = [...heroSource].sort(() => Math.random() - 0.5).slice(0, heroImages.length);
    heroSources = picks.map((photo) => gridSource(photo));
    heroAlts = picks.map((photo) => photo.title || photo.filename || "自然风光作品");
  }

  heroImages.forEach((image, index) => {
    const src = heroSources[index % Math.max(heroSources.length, 1)];
    if (!src) return;
    image.src = src;
    image.alt = heroAlts[index % Math.max(heroAlts.length, 1)] || "";
    image.decoding = "async";
    image.loading = "eager";
    image.fetchPriority = index < 2 ? "high" : "auto";
  });

  portfolioProjects = projectList.length
    ? projectList.map(projectToWork)
    : topicList.map(topicToWork);
  visibleWorks = [...portfolioProjects];

  const projectPhotoTotal = projectList.length
    ? projectList.reduce((sum, project) => sum + project.count, 0)
    : visibleWorks.reduce((sum, work) => sum + (Number.parseInt(work.count, 10) || 0), 0);
  setMetric(document.querySelector("#projectCountMetric"), visibleWorks.length);
  setMetric(document.querySelector("#projectPhotoMetric"), projectPhotoTotal);

  if (collectionGrid) {
    collectionGrid.innerHTML = topicList
      .map((topic, index) => {
        const cover = pickRandomPhoto(topic.photos);
        const tileClass = index === 0 ? "collection-tile large" : "collection-tile";
        return `
          <button class="${tileClass}" type="button" data-filter-jump="${topic.key}">
            <img src="${gridSource(cover)}" alt="${topic.label}" loading="lazy" decoding="async" />
            <span>
              <small>${String(index + 1).padStart(2, "0")}</small>
              <strong>${topic.label}</strong>
              <em>${topic.count} 张作品</em>
            </span>
          </button>
        `;
      })
      .join("");
  }

  if (projectList.length) {
    rebuildWorkFilters(projectList);
  } else {
    rebuildWorkFilters(topicList.map((topic) => ({ id: topic.key, label: topic.label })));
  }

  // Select by class: the markup ships without data-count-target precisely so a
  // stale number can never be rendered before this runs.
  const topicMetrics = document.querySelectorAll(".stats-strip .metric");
  setMetric(topicMetrics[0], topicList.length);
  setMetric(topicMetrics[1], topicList.reduce((sum, topic) => sum + topic.count, 0));

  return true;
}

function renderGallery(filter = "all") {
  if (!gallery) return;
  visibleWorks = [...portfolioProjects];

  if (filter !== "all") {
    visibleWorks = visibleWorks.filter((work) => work.categoryLabel === filter || work.id === filter);
  }

  gallery.innerHTML = visibleWorks
    .map(
      (work, index) => `
        <button class="photo-card project-card-large reveal" type="button" data-index="${index}" data-project-id="${work.id}" aria-label="查看项目：${work.title}">
          <img src="${work.thumb}" alt="${work.alt}" loading="lazy" decoding="async">
          <span class="photo-info">
            <small>${work.categoryLabel} · ${work.location} · ${work.count}</small>
            <strong>${work.title}</strong>
            <em>${work.story}</em>
          </span>
        </button>
      `
    )
    .join("");

  observeReveal();
}

function openLightbox(index) {
  activeIndex = index;
  const work = visibleWorks[activeIndex];
  if (!work) return;
  lightboxImage.decoding = "async";
  lightboxImage.src = work.large;
  lightboxImage.alt = work.alt;
  lightboxTitle.textContent = work.title;
  lightboxMeta.textContent = `${work.categoryLabel} · ${work.location}`;
  lightboxStory.textContent = work.story;
  lightbox.showModal();
}

function changeLightbox(step) {
  if (!visibleWorks.length) return;
  activeIndex = (activeIndex + step + visibleWorks.length) % visibleWorks.length;
  openLightbox(activeIndex);
}

function setActiveFilter(filter) {
  filterButtons.forEach((item) => {
    item.classList.toggle("active", item.dataset.filter === filter);
  });
  renderGallery(filter);
}

/**
 * 提交反馈条。分成功与失败两种状态 —— 成功文案取自页面里的初始内容（不改 HTML 就能改文案），
 * 失败文案必须给出**可用的替代路径**，因为访客看到「没送达」之后得知道下一步找谁。
 *
 * 失败态停留更久（7s）并且可交互：成功态是纯通知，保持 pointer-events: none。
 */
const IDEA_TOAST_COPY = {
  ok: { title: "", body: "" },
  error: {
    title: "提交没能送达",
    body: `页面暂时收不到这条消息，请直接邮件联系 ${CONTACT_EMAIL}，或加微信 ${CONTACT_WECHAT}。`,
  },
};

function showIdeaToast(state) {
  if (!ideaToast) return;
  const strong = ideaToast.querySelector("strong");
  const span = ideaToast.querySelector("span");
  if (strong && span) {
    if (!IDEA_TOAST_COPY.ok.title) {
      IDEA_TOAST_COPY.ok.title = strong.textContent;
      IDEA_TOAST_COPY.ok.body = span.textContent;
    }
    const copy = IDEA_TOAST_COPY[state] || IDEA_TOAST_COPY.ok;
    strong.textContent = copy.title;
    span.textContent = copy.body;
  }

  ideaToast.classList.toggle("is-error", state === "error");
  ideaToast.hidden = false;
  window.requestAnimationFrame(() => {
    ideaToast.classList.add("is-visible");
  });
  window.clearTimeout(showIdeaToast.timer);
  showIdeaToast.timer = window.setTimeout(() => {
    ideaToast.classList.remove("is-visible");
    window.setTimeout(() => {
      ideaToast.hidden = true;
    }, 240);
  }, state === "error" ? 7000 : 3200);
}

/**
 * 提交想法。**必须区分成功与失败**：这套页面同时发在 Netlify（表单有接收端）和
 * Cloudflare（纯静态资源，POST 到 / 会得到 405）上。原先无论结果如何都提示「感谢你的意见」，
 * 于是在 Cloudflare 上访客以为已送达、实际一个字节都没存下来，双方都不知道丢了。
 *
 * 返回 true 表示接收端已确认（HTTP 2xx）；否则抛出，由调用处切换到失败提示。
 * 本地以 file:// 打开时没有后端属正常，按预览处理，不报错。
 */
async function submitIdeaForm(formData) {
  if (window.location.protocol === "file:") return true;
  const response = await fetch("/", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams(formData).toString(),
  });
  if (!response.ok) {
    throw new Error(`表单提交失败：HTTP ${response.status}`);
  }
  return true;
}

/**
 * 首页拼贴轮播：只在 hero-sets.js 的预制组之间按顺序切换。
 *
 * 旧实现是从自然风光原片池里随机抽 6 张、每 2 秒换一次。原片是 24 MP、
 * 单张最大 23 MB，于是每 2 秒要下载约 45 MB、解码约 576 MB 位图（单张解码后
 * 就是 6000×4000×4 ≈ 96 MB），浏览器内存一直被推着走，页面自然卡。
 *
 * 现在换成 4 组预制小图（长边 960px webp，24 张合计约 2.3 MB）：
 *   - 切换前先把整组解码完，换图瞬间不会有空白帧；
 *   - 首屏渲染后趁空闲把其余三组读完，之后切换不再产生任何网络请求；
 *   - 拼贴滚出视口就停止换图，避免用户在下面看作品集时白跑动画。
 *
 * 没有 hero-sets.js 时不做轮播：宁可静态，也不退回“每 2 秒下 45 MB”那条路。
 */
function initHeroAutoGallery() {
  if (!heroImages.length || !heroSets.length) return;
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

  const SWAP_INTERVAL = 5000;
  const FADE_STAGGER = 80;
  const FADE_HOLD = 130;

  let currentIndex = 0;
  let intervalId = null;
  let swapping = false;
  const decoded = new Map();

  function preloadSource(src) {
    if (decoded.has(src)) return decoded.get(src);

    const request = new Promise((resolve) => {
      const image = new Image();
      let settled = false;
      let timer = null;

      const done = () => {
        if (settled) return;
        settled = true;
        window.clearTimeout(timer);
        resolve();
      };

      // 兜底：图片既不 onload 也不 onerror（请求卡住/解码不返回）时，绝不能让
      // 调用方永远等下去——swapping 一旦卡在 true，轮播就再也不会动了。
      timer = window.setTimeout(done, 8000);

      image.decoding = "async";
      image.onload = () => {
        if (image.decode) {
          image.decode().then(done, done);
        } else {
          done();
        }
      };
      image.onerror = done;
      image.src = src;
    });

    decoded.set(src, request);
    return request;
  }

  function preloadSet(set) {
    return Promise.all(set.images.map((item) => preloadSource(item.src)));
  }

  /** 逐格错开地做一次「压暗—换图—复原」，比 6 格同时硬切自然得多。 */
  function applySet(set) {
    heroImages.forEach((image, index) => {
      const item = set.images[index];
      if (!item) return;

      window.setTimeout(() => {
        image.classList.add("is-fading");
        window.setTimeout(() => {
          image.src = item.src;
          image.alt = item.alt || "";
          image.classList.remove("is-fading");
        }, FADE_HOLD);
      }, index * FADE_STAGGER);
    });
  }

  async function swapToNextSet() {
    if (swapping) return;
    swapping = true;

    const nextIndex = (currentIndex + 1) % heroSets.length;
    await preloadSet(heroSets[nextIndex]); // 先解码完再换，杜绝空白帧
    applySet(heroSets[nextIndex]);
    currentIndex = nextIndex;

    const settle = FADE_HOLD + heroImages.length * FADE_STAGGER + 220;
    window.setTimeout(() => {
      swapping = false;
      preloadSet(heroSets[(currentIndex + 1) % heroSets.length]);
    }, settle);
  }

  function start() {
    if (intervalId) return;
    intervalId = window.setInterval(swapToNextSet, SWAP_INTERVAL);
  }

  function stop() {
    if (!intervalId) return;
    window.clearInterval(intervalId);
    intervalId = null;
  }

  document.addEventListener("visibilitychange", () => {
    if (document.hidden) {
      stop();
    } else {
      start();
    }
  });

  const collage = document.querySelector(".collage");
  if (collage && "IntersectionObserver" in window) {
    new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => (entry.isIntersecting ? start() : stop()));
      },
      { threshold: 0 }
    ).observe(collage);
  }

  // 首屏渲染完再预热其余三组，别和首屏抢带宽。
  const warmRemainingSets = () => heroSets.slice(1).forEach(preloadSet);
  if ("requestIdleCallback" in window) {
    window.requestIdleCallback(warmRemainingSets, { timeout: 4000 });
  } else {
    window.setTimeout(warmRemainingSets, 1500);
  }

  start();
}

function observeReveal() {
  const items = document.querySelectorAll(".reveal:not(.visible)");
  if (!("IntersectionObserver" in window)) {
    items.forEach((item) => item.classList.add("visible"));
    return;
  }

  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("visible");
          observer.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.12 }
  );

  items.forEach((item) => observer.observe(item));
}

function initStatsCounter() {
  const statStrips = [...document.querySelectorAll(".stats-strip, .work-stats")];
  const counters = [...document.querySelectorAll(".metric[data-count-target]")];
  if (!statStrips.length || !counters.length) return;

  const prefersReducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  function setFinalValues() {
    counters.forEach((counter) => {
      counter.textContent = counter.dataset.countTarget;
    });
  }

  if (prefersReducedMotion || !("IntersectionObserver" in window)) {
    setFinalValues();
    return;
  }

  counters.forEach((counter) => {
    counter.textContent = "0";
  });

  function animateCounter(counter) {
    const target = Number(counter.dataset.countTarget);
    if (!Number.isFinite(target)) {
      counter.textContent = counter.dataset.countTarget;
      return;
    }
    const duration = 1100;
    const startTime = performance.now();

    function update(now) {
      const progress = Math.min((now - startTime) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      counter.textContent = Math.round(target * eased).toString();

      if (progress < 1) {
        window.requestAnimationFrame(update);
      } else {
        counter.textContent = target.toString();
      }
    }

    window.requestAnimationFrame(update);
  }

  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        entry.target.querySelectorAll(".metric[data-count-target]").forEach(animateCounter);
        observer.unobserve(entry.target);
      });
    },
    { threshold: 0.35 }
  );

  statStrips.forEach((strip) => observer.observe(strip));
}

function initSectionTransitions() {
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

  const sections = [...document.querySelectorAll("main > section")];
  let ticking = false;

  function setActiveNav(id) {
    navLinks.forEach((link) => {
      link.classList.toggle("active", link.getAttribute("href") === `#${id}`);
    });
  }

  function updateSectionMotion() {
    ticking = false;
    const viewportHeight = window.innerHeight || document.documentElement.clientHeight;
    const viewportCenter = viewportHeight / 2;
    let activeSection = null;
    let activeDistance = Number.POSITIVE_INFINITY;

    sections.forEach((section) => {
      const rect = section.getBoundingClientRect();
      const sectionCenter = rect.top + rect.height / 2;
      const distance = Math.abs(sectionCenter - viewportCenter);
      const intersectsViewport = rect.bottom > 0 && rect.top < viewportHeight;
      if (intersectsViewport && section.id && distance < activeDistance) {
        activeSection = section;
        activeDistance = distance;
      }
    });

    if (activeSection) {
      setActiveNav(activeSection.id);
    }
  }

  function requestSectionMotionUpdate() {
    if (ticking) return;
    ticking = true;
    window.requestAnimationFrame(updateSectionMotion);
  }

  window.addEventListener("scroll", requestSectionMotionUpdate, { passive: true });
  window.addEventListener("resize", requestSectionMotionUpdate);
  updateSectionMotion();

  navLinks.forEach((link) => {
    link.addEventListener("click", () => {
      const target = document.querySelector(link.getAttribute("href"));
      if (!target) return;

      window.setTimeout(() => {
        target.classList.remove("section-focus-fade");
        void target.offsetWidth;
        target.classList.add("section-focus-fade");
        setActiveNav(target.id);
        requestSectionMotionUpdate();
      }, 260);
    });
  });

  if (window.location.hash) {
    const initialTarget = document.querySelector(window.location.hash);
    if (initialTarget) {
      window.setTimeout(() => {
        initialTarget.classList.add("section-focus-fade");
        setActiveNav(initialTarget.id);
        requestSectionMotionUpdate();
      }, 320);
    }
  }
}

function rebuildContactSection() {
  const contact = document.querySelector("#contact");
  if (!contact) return;

  contact.innerHTML = `
    <article class="contact-card">
      <section class="contact-column bio-column" aria-label="摄影师介绍">
        <img
          class="contact-bio-image"
          src="assets/contact-dino-avatar.svg"
          alt="可爱漫画小恐龙头像"
        />
        <div>
          <p class="eyebrow">Photographer</p>
          <h2>承瑀</h2>
          <p>因为早年间留过学，成了对生活有点爱好和要求的小登。平时喜欢在与世隔绝的山里、无人问津的城墙角落溜达。人生的乐趣在于没苦硬吃。如果你能欣赏我的照片和理念，那我们也是一类人，欢迎来和我聊聊。</p>
        </div>
      </section>
      <section class="contact-column social-column" aria-label="社交媒体关注">
        <p class="eyebrow">Follow</p>
        <h3>社交媒体</h3>
        <div class="social-stack">
          <a class="social-profile" href="https://www.xiaohongshu.com" target="_blank" rel="noreferrer">
            <span class="social-logo xhs-logo">RED</span>
            <span>
              <strong>小红书</strong>
              <small>RED ID: thomas_pics</small>
            </span>
          </a>
          <a class="social-profile" href="https://www.instagram.com" target="_blank" rel="noreferrer">
            <span class="social-logo ig-logo">IG</span>
            <span>
              <strong>Instagram</strong>
              <small>@thomas.pics</small>
            </span>
          </a>
        </div>
      </section>
      <section class="contact-column wechat-column" aria-label="预约方式">
        <p class="eyebrow">Booking</p>
        <img
          class="wechat-qr"
          src="assets/wechat-qr.png"
          alt="承瑀的微信预约二维码，用微信扫码添加"
          width="594"
          height="594"
          loading="lazy"
        />
        <strong>微信预约</strong>
        <small>微信扫码添加，或搜索 WeChat: ${CONTACT_WECHAT}</small>
        <div class="direct-contact">
          <a class="mail-link" href="mailto:${CONTACT_EMAIL}?subject=%E6%8B%8D%E6%91%84%E9%A2%84%E7%BA%A6">${CONTACT_EMAIL}</a>
        </div>
      </section>
    </article>
  `;
}

filterBar?.addEventListener("click", (event) => {
  const button = event.target.closest(".filter-button");
  if (!button) return;
  setActiveFilter(button.dataset.filter);
});

collectionGrid?.addEventListener("click", (event) => {
  const tile = event.target.closest("[data-filter-jump]");
  if (!tile) return;
  window.location.href = `portfolio.html?category=${encodeURIComponent(tile.dataset.filterJump)}`;
});

gallery?.addEventListener("click", (event) => {
  const card = event.target.closest(".photo-card");
  if (!card) return;
  if (card.dataset.projectId) {
    window.location.href = `portfolio.html?project=${encodeURIComponent(card.dataset.projectId)}`;
    return;
  }

  openLightbox(Number(card.dataset.index));
});

projectForm?.addEventListener("submit", (event) => {
  event.preventDefault();
  const formData = new FormData(projectForm);
  const place = formData.get("city").toString().trim();
  const theme = formData.get("theme").toString().trim();

  if (!place || !theme) return;

  submitIdeaForm(formData)
    .then(() => showIdeaToast("ok"))
    .catch(() => showIdeaToast("error"))
    .finally(() => {
      projectForm.reset();
    });
});

document.querySelector(".close-lightbox").addEventListener("click", () => lightbox.close());
document.querySelector(".lightbox-prev").addEventListener("click", () => changeLightbox(-1));
document.querySelector(".lightbox-next").addEventListener("click", () => changeLightbox(1));

document.addEventListener("keydown", (event) => {
  if (!lightbox.open) return;
  if (event.key === "ArrowLeft") changeLightbox(-1);
  if (event.key === "ArrowRight") changeLightbox(1);
});

const yearNode = document.querySelector("#year");
if (yearNode) yearNode.textContent = new Date().getFullYear();

rebuildContactSection();
hydrateSiteFromPhotoLibrary();
initHeroAutoGallery();
renderGallery();
initSectionTransitions();
initStatsCounter();
observeReveal();
