/**
 * Thomas pics — homepage behaviour.
 *
 * All content comes from `window.PHOTO_LIBRARY`, which is generated by
 * `scripts/optimize_images.py` and mirrors the folders under `assets/photos/`.
 * There is deliberately no sample/placeholder content in this file: if the
 * library is missing, the page says so instead of inventing projects.
 */

const PLACEHOLDER_COPY = {
  nature: "山野、海岸、湖泊与季节光线构成的自然影像档案。",
  city: "街道、建筑、灯光与人群移动之间的城市节奏。",
  people: "人物、现场与真实关系共同组成的纪实肖像。",
  events: "活动、会议与集体现场中的秩序、表情和瞬间。",
};

const PROJECT_GROUP_LABEL = "沉浸式作品集";

const gallery = document.querySelector("#gallery");
const filterBar = document.querySelector(".filter-bar");
let filterButtons = [...document.querySelectorAll(".filter-button")];
const collectionGrid = document.querySelector(".collection-grid");
const navLinks = [...document.querySelectorAll(".nav-links a[href^='#']")];
const lightbox = document.querySelector("#lightbox");
const lightboxImage = document.querySelector("#lightboxImage");
const lightboxTitle = document.querySelector("#lightboxTitle");
const lightboxMeta = document.querySelector("#lightboxMeta");
const lightboxStory = document.querySelector("#lightboxStory");
const projectForm = document.querySelector("#projectForm");
const projectBoard = document.querySelector("#projectBoard");
const ideaToast = document.querySelector("#ideaToast");
const heroImages = [...document.querySelectorAll(".collage-image")];

let heroPhotoPool = [];
let portfolioProjects = [];
let visibleWorks = [];
let activeIndex = 0;
let heroSwapLocked = false;

function getPhotoLibrary() {
  return window.PHOTO_LIBRARY || null;
}

/** Grids and hero tiles want the small derivative; masters are 4-33 MB. */
function gridSource(photo) {
  return photo?.thumb || photo?.src || "";
}

/** The lightbox wants the big derivative, falling back to the master. */
function largeSource(photo) {
  return photo?.large || photo?.src || "";
}

function pickRandomPhoto(items) {
  if (!items?.length) return null;
  return items[Math.floor(Math.random() * items.length)];
}

function topicToWork(topic) {
  const cover = pickRandomPhoto(topic.photos);
  return {
    id: `topic-${topic.key}`,
    title: topic.title || topic.label,
    categoryLabel: topic.label,
    location: "本地图库",
    count: `${topic.count} 张`,
    thumb: gridSource(cover),
    large: largeSource(cover),
    src: cover?.src || "",
    alt: cover?.title || topic.title || topic.label,
    story: topic.intro || PLACEHOLDER_COPY[topic.key] || `${topic.label}，共 ${topic.count} 张作品。`,
  };
}

function projectToWork(project) {
  const cover = project.photos?.find((photo) => photo.src === project.cover) || pickRandomPhoto(project.photos);
  return {
    id: project.id || project.key,
    title: project.title || project.label,
    categoryLabel: project.label || project.title,
    groupLabel: PROJECT_GROUP_LABEL,
    location: project.chapters?.length ? project.chapters.join(" / ") : "本地项目",
    count: `${project.count} 张`,
    thumb: gridSource(cover),
    large: largeSource(cover),
    src: cover?.src || "",
    alt: cover?.title || project.title || project.label,
    story: project.intro || `${project.label || project.title}，共 ${project.count} 张作品。`,
  };
}

function rebuildWorkFilters(projectList) {
  if (!filterBar || !projectList?.length) return;
  filterBar.innerHTML = [
    `<button class="filter-button active" type="button" data-filter="all">全部</button>`,
    ...projectList.map(
      (project) =>
        `<button class="filter-button" type="button" data-filter="${project.id || project.key}">${
          project.label || project.title
        }</button>`
    ),
  ].join("");
  filterButtons = [...document.querySelectorAll(".filter-button")];
}

function setMetric(node, value) {
  if (!node) return;
  node.dataset.countTarget = String(value);
  node.textContent = String(value);
}

function renderLibraryMissing() {
  if (gallery) {
    gallery.innerHTML = `
      <p class="library-missing">
        图库数据未加载。请先运行 <code>python scripts/optimize_images.py</code> 重新生成
        <code>photo-data.js</code>。
      </p>
    `;
  }
  if (projectBoard) {
    projectBoard.innerHTML = `<p class="library-missing">暂无可展示的项目。</p>`;
  }
  const metrics = document.querySelectorAll(".metric[data-count-target]");
  metrics.forEach((metric) => {
    metric.dataset.countTarget = "0";
    metric.textContent = "0";
  });
}

function hydrateSiteFromPhotoLibrary() {
  const library = getPhotoLibrary();
  const topics = library?.topics;
  if (!topics) {
    renderLibraryMissing();
    return false;
  }

  const topicList = Object.values(topics).filter((topic) => topic.photos?.length);
  const projectList = Object.values(library.projects || {}).filter((project) => project.photos?.length);
  if (!topicList.length && !projectList.length) {
    renderLibraryMissing();
    return false;
  }

  // Hero collage draws from the landscape collection, falling back to anything.
  const heroSource = (topics.nature?.photos?.length ? topics.nature.photos : topicList.flatMap((t) => t.photos));
  heroPhotoPool = heroSource.map((photo) => gridSource(photo)).filter(Boolean);
  const firstHeroSet = [...heroSource].sort(() => Math.random() - 0.5).slice(0, heroImages.length);
  heroImages.forEach((image, index) => {
    const photo = firstHeroSet[index % Math.max(firstHeroSet.length, 1)];
    if (!photo) return;
    image.src = gridSource(photo);
    image.alt = photo.title || photo.filename || "自然风光作品";
    image.decoding = "async";
    image.loading = "eager";
    image.fetchPriority = index < 2 ? "high" : "auto";
  });

  portfolioProjects = projectList.length
    ? projectList.map(projectToWork)
    : topicList.map(topicToWork);
  visibleWorks = [...portfolioProjects];

  const projectPhotoTotal = projectList.length
    ? projectList.reduce((sum, project) => sum + project.count, 0)
    : visibleWorks.reduce((sum, work) => sum + (Number.parseInt(work.count, 10) || 0), 0);
  setMetric(document.querySelector("#projectCountMetric"), visibleWorks.length);
  setMetric(document.querySelector("#projectPhotoMetric"), projectPhotoTotal);

  if (collectionGrid) {
    collectionGrid.innerHTML = topicList
      .map((topic, index) => {
        const cover = pickRandomPhoto(topic.photos);
        const tileClass = index === 0 ? "collection-tile large" : "collection-tile";
        return `
          <button class="${tileClass}" type="button" data-filter-jump="${topic.key}">
            <img src="${gridSource(cover)}" alt="${topic.label}" loading="lazy" />
            <span>
              <small>${String(index + 1).padStart(2, "0")}</small>
              <strong>${topic.label}</strong>
              <em>${topic.count} 张作品</em>
            </span>
          </button>
        `;
      })
      .join("");
  }

  if (projectList.length) {
    rebuildWorkFilters(projectList);
  } else {
    rebuildWorkFilters(topicList.map((topic) => ({ id: topic.key, label: topic.label })));
  }

  // Select by class: the markup ships without data-count-target precisely so a
  // stale number can never be rendered before this runs.
  const topicMetrics = document.querySelectorAll(".stats-strip .metric");
  setMetric(topicMetrics[0], topicList.length);
  setMetric(topicMetrics[1], topicList.reduce((sum, topic) => sum + topic.count, 0));

  return true;
}

function renderProjects() {
  if (!projectBoard) return;
  const library = getPhotoLibrary();
  const projects = library ? Object.values(library.projects || {}).filter((p) => p.photos?.length) : [];

  if (!projects.length) {
    projectBoard.innerHTML = `<p class="library-missing">暂无进行中的项目。</p>`;
    return;
  }

  projectBoard.innerHTML = projects
    .slice(0, 3)
    .map((project, index) => {
      const cover = project.photos.find((photo) => photo.src === project.cover) || project.photos[0];
      const chapters = project.chapters?.length ? project.chapters.join(" · ") : `${project.count} 张作品`;
      return `
        <a class="project-card" href="portfolio.html?project=${encodeURIComponent(project.id || project.key)}">
          <img src="${gridSource(cover)}" alt="${project.title || project.label}" loading="lazy" />
          <span>Project ${String(index + 1).padStart(2, "0")}</span>
          <h3>${project.title || project.label}</h3>
          <p>${project.intro || ""}</p>
          <small>${chapters}</small>
        </a>
      `;
    })
    .join("");
}

function renderGallery(filter = "all") {
  if (!gallery) return;
  visibleWorks = [...portfolioProjects];

  if (filter !== "all") {
    visibleWorks = visibleWorks.filter((work) => work.categoryLabel === filter || work.id === filter);
  }

  gallery.innerHTML = visibleWorks
    .map(
      (work, index) => `
        <button class="photo-card project-card-large reveal" type="button" data-index="${index}" data-project-id="${work.id}" aria-label="查看项目：${work.title}">
          <img src="${work.thumb}" alt="${work.alt}" loading="lazy">
          <span class="photo-info">
            <small>${work.categoryLabel} · ${work.location} · ${work.count}</small>
            <strong>${work.title}</strong>
            <em>${work.story}</em>
          </span>
        </button>
      `
    )
    .join("");

  observeReveal();
}

function openLightbox(index) {
  activeIndex = index;
  const work = visibleWorks[activeIndex];
  if (!work) return;
  lightboxImage.src = work.large;
  lightboxImage.alt = work.alt;
  lightboxTitle.textContent = work.title;
  lightboxMeta.textContent = `${work.categoryLabel} · ${work.location}`;
  lightboxStory.textContent = work.story;
  lightbox.showModal();
}

function changeLightbox(step) {
  if (!visibleWorks.length) return;
  activeIndex = (activeIndex + step + visibleWorks.length) % visibleWorks.length;
  openLightbox(activeIndex);
}

function setActiveFilter(filter) {
  filterButtons.forEach((item) => {
    item.classList.toggle("active", item.dataset.filter === filter);
  });
  renderGallery(filter);
}

function showIdeaThanks() {
  if (!ideaToast) return;
  ideaToast.hidden = false;
  window.requestAnimationFrame(() => {
    ideaToast.classList.add("is-visible");
  });
  window.clearTimeout(showIdeaThanks.timer);
  showIdeaThanks.timer = window.setTimeout(() => {
    ideaToast.classList.remove("is-visible");
    window.setTimeout(() => {
      ideaToast.hidden = true;
    }, 240);
  }, 3200);
}

async function submitIdeaForm(formData) {
  if (window.location.protocol === "file:") return;
  await fetch("/", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams(formData).toString(),
  });
}

function initHeroAutoGallery() {
  if (!heroImages.length || !heroPhotoPool.length) return;
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

  let visibleSources = heroImages.map((image) => image.src);
  let intervalId = null;
  let preloadQueue = Promise.resolve();
  const decodedImages = new Map();

  function shuffleSources(sources) {
    const shuffled = [...sources];
    for (let index = shuffled.length - 1; index > 0; index -= 1) {
      const nextIndex = Math.floor(Math.random() * (index + 1));
      [shuffled[index], shuffled[nextIndex]] = [shuffled[nextIndex], shuffled[index]];
    }
    return shuffled;
  }

  function pickNextSourceSet() {
    const unseenSources = heroPhotoPool.filter((src) => !visibleSources.includes(src));
    const sourceList = unseenSources.length >= heroImages.length ? unseenSources : heroPhotoPool;
    return shuffleSources(sourceList).slice(0, heroImages.length);
  }

  function preloadSource(src) {
    if (decodedImages.has(src)) return decodedImages.get(src);

    const request = new Promise((resolve) => {
      const image = new Image();
      image.decoding = "async";
      image.fetchPriority = "low";
      image.onload = () => {
        if (image.decode) {
          image.decode().then(resolve).catch(resolve);
        } else {
          resolve();
        }
      };
      image.onerror = resolve;
      image.src = src;
    });

    decodedImages.set(src, request);
    return request;
  }

  function trimPreloadCache() {
    if (decodedImages.size <= 30) return;
    const keep = new Set([...visibleSources, ...heroPhotoPool.slice(0, 12)]);
    [...decodedImages.keys()].forEach((src) => {
      if (!keep.has(src)) decodedImages.delete(src);
    });
  }

  function warmNextHeroImages() {
    const nextSources = pickNextSourceSet();
    preloadQueue = Promise.all(nextSources.map(preloadSource)).then(() => nextSources);
  }

  async function swapAllHeroImages() {
    if (heroSwapLocked) return;

    heroSwapLocked = true;
    const nextSources = await preloadQueue;
    preloadQueue = Promise.resolve(nextSources);

    heroImages.forEach((image) => {
      image.classList.add("is-swapping");
    });
    window.setTimeout(() => {
      heroImages.forEach((image, index) => {
        image.src = nextSources[index];
        image.classList.remove("is-swapping");
      });
      visibleSources = [...nextSources];
      trimPreloadCache();
      warmNextHeroImages();
    }, 260);

    window.setTimeout(() => {
      heroSwapLocked = false;
    }, 620);
  }

  function startAutoSwap() {
    if (intervalId) return;
    intervalId = window.setInterval(swapAllHeroImages, 2000);
  }

  function stopAutoSwap() {
    if (!intervalId) return;
    window.clearInterval(intervalId);
    intervalId = null;
  }

  document.addEventListener("visibilitychange", () => {
    if (document.hidden) {
      stopAutoSwap();
    } else {
      startAutoSwap();
    }
  });

  heroImages.forEach((image) => {
    image.decoding = "async";
    image.loading = "eager";
  });
  warmNextHeroImages();
  startAutoSwap();
}

function observeReveal() {
  const items = document.querySelectorAll(".reveal:not(.visible)");
  if (!("IntersectionObserver" in window)) {
    items.forEach((item) => item.classList.add("visible"));
    return;
  }

  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("visible");
          observer.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.12 }
  );

  items.forEach((item) => observer.observe(item));
}

function initStatsCounter() {
  const statStrips = [...document.querySelectorAll(".stats-strip, .work-stats")];
  const counters = [...document.querySelectorAll(".metric[data-count-target]")];
  if (!statStrips.length || !counters.length) return;

  const prefersReducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  function setFinalValues() {
    counters.forEach((counter) => {
      counter.textContent = counter.dataset.countTarget;
    });
  }

  if (prefersReducedMotion || !("IntersectionObserver" in window)) {
    setFinalValues();
    return;
  }

  counters.forEach((counter) => {
    counter.textContent = "0";
  });

  function animateCounter(counter) {
    const target = Number(counter.dataset.countTarget);
    if (!Number.isFinite(target)) {
      counter.textContent = counter.dataset.countTarget;
      return;
    }
    const duration = 1100;
    const startTime = performance.now();

    function update(now) {
      const progress = Math.min((now - startTime) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      counter.textContent = Math.round(target * eased).toString();

      if (progress < 1) {
        window.requestAnimationFrame(update);
      } else {
        counter.textContent = target.toString();
      }
    }

    window.requestAnimationFrame(update);
  }

  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        entry.target.querySelectorAll(".metric[data-count-target]").forEach(animateCounter);
        observer.unobserve(entry.target);
      });
    },
    { threshold: 0.35 }
  );

  statStrips.forEach((strip) => observer.observe(strip));
}

function initSectionTransitions() {
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

  const sections = [...document.querySelectorAll("main > section")];
  let ticking = false;

  function setActiveNav(id) {
    navLinks.forEach((link) => {
      link.classList.toggle("active", link.getAttribute("href") === `#${id}`);
    });
  }

  function updateSectionMotion() {
    ticking = false;
    const viewportHeight = window.innerHeight || document.documentElement.clientHeight;
    const viewportCenter = viewportHeight / 2;
    let activeSection = null;
    let activeDistance = Number.POSITIVE_INFINITY;

    sections.forEach((section) => {
      const rect = section.getBoundingClientRect();
      const sectionCenter = rect.top + rect.height / 2;
      const distance = Math.abs(sectionCenter - viewportCenter);
      const intersectsViewport = rect.bottom > 0 && rect.top < viewportHeight;
      if (intersectsViewport && section.id && distance < activeDistance) {
        activeSection = section;
        activeDistance = distance;
      }
    });

    if (activeSection) {
      setActiveNav(activeSection.id);
    }
  }

  function requestSectionMotionUpdate() {
    if (ticking) return;
    ticking = true;
    window.requestAnimationFrame(updateSectionMotion);
  }

  window.addEventListener("scroll", requestSectionMotionUpdate, { passive: true });
  window.addEventListener("resize", requestSectionMotionUpdate);
  updateSectionMotion();

  navLinks.forEach((link) => {
    link.addEventListener("click", () => {
      const target = document.querySelector(link.getAttribute("href"));
      if (!target) return;

      window.setTimeout(() => {
        target.classList.remove("section-focus-fade");
        void target.offsetWidth;
        target.classList.add("section-focus-fade");
        setActiveNav(target.id);
        requestSectionMotionUpdate();
      }, 260);
    });
  });

  if (window.location.hash) {
    const initialTarget = document.querySelector(window.location.hash);
    if (initialTarget) {
      window.setTimeout(() => {
        initialTarget.classList.add("section-focus-fade");
        setActiveNav(initialTarget.id);
        requestSectionMotionUpdate();
      }, 320);
    }
  }
}

function rebuildContactSection() {
  const contact = document.querySelector("#contact");
  if (!contact) return;

  contact.innerHTML = `
    <article class="contact-card">
      <section class="contact-column bio-column" aria-label="摄影师介绍">
        <img
          class="contact-bio-image"
          src="assets/contact-dino-avatar.svg"
          alt="可爱漫画小恐龙头像"
        />
        <div>
          <p class="eyebrow">Photographer</p>
          <h2>承瑀</h2>
          <p>承瑀摄影 Thomas pics，关注自然光、城市生活和人物关系。作品覆盖山野、城市、人像与活动记录。</p>
        </div>
      </section>
      <section class="contact-column social-column" aria-label="社交媒体关注">
        <p class="eyebrow">Follow</p>
        <h3>社交媒体</h3>
        <div class="social-stack">
          <a class="social-profile" href="https://www.xiaohongshu.com" target="_blank" rel="noreferrer">
            <span class="social-logo xhs-logo">RED</span>
            <span>
              <strong>小红书</strong>
              <small>RED ID: thomas_pics</small>
            </span>
          </a>
          <a class="social-profile" href="https://www.instagram.com" target="_blank" rel="noreferrer">
            <span class="social-logo ig-logo">IG</span>
            <span>
              <strong>Instagram</strong>
              <small>@thomas.pics</small>
            </span>
          </a>
        </div>
      </section>
      <section class="contact-column wechat-column" aria-label="预约方式">
        <p class="eyebrow">Booking</p>
        <div class="qr-placeholder" aria-hidden="true">
          <span></span><span></span><span></span><span></span><span></span><span></span>
        </div>
        <strong>微信预约</strong>
        <small>WeChat: chengyu_95</small>
        <div class="direct-contact">
          <a href="mailto:605710591@qq.com">605710591@qq.com</a>
          <a href="tel:+8613319119096">13319119096</a>
        </div>
      </section>
    </article>
  `;
}

filterBar?.addEventListener("click", (event) => {
  const button = event.target.closest(".filter-button");
  if (!button) return;
  setActiveFilter(button.dataset.filter);
});

collectionGrid?.addEventListener("click", (event) => {
  const tile = event.target.closest("[data-filter-jump]");
  if (!tile) return;
  window.location.href = `portfolio.html?category=${encodeURIComponent(tile.dataset.filterJump)}`;
});

gallery?.addEventListener("click", (event) => {
  const card = event.target.closest(".photo-card");
  if (!card) return;
  if (card.dataset.projectId) {
    window.location.href = `portfolio.html?project=${encodeURIComponent(card.dataset.projectId)}`;
    return;
  }

  openLightbox(Number(card.dataset.index));
});

projectForm?.addEventListener("submit", (event) => {
  event.preventDefault();
  const formData = new FormData(projectForm);
  const place = formData.get("city").toString().trim();
  const theme = formData.get("theme").toString().trim();

  if (!place || !theme) return;

  submitIdeaForm(formData)
    .catch(() => {})
    .finally(() => {
      showIdeaThanks();
      projectForm.reset();
    });
});

document.querySelector(".close-lightbox").addEventListener("click", () => lightbox.close());
document.querySelector(".lightbox-prev").addEventListener("click", () => changeLightbox(-1));
document.querySelector(".lightbox-next").addEventListener("click", () => changeLightbox(1));

document.addEventListener("keydown", (event) => {
  if (!lightbox.open) return;
  if (event.key === "ArrowLeft") changeLightbox(-1);
  if (event.key === "ArrowRight") changeLightbox(1);
});

const yearNode = document.querySelector("#year");
if (yearNode) yearNode.textContent = new Date().getFullYear();

rebuildContactSection();
hydrateSiteFromPhotoLibrary();
initHeroAutoGallery();
renderGallery();
renderProjects();
initSectionTransitions();
initStatsCounter();
observeReveal();
