#!/usr/bin/env python3
"""Bind this repository to WebP derivatives of the published originals.

Why this exists
---------------
Cloudflare Pages builds this repository and publishes what it finds there, so
this repo *is* the published tree -- the bytes committed here are the bytes a
visitor downloads. Camera originals cannot be committed. There are 346 of them,
2.1 GB:

* A first push has to move about 2 GB over HTTPS, which routinely times out.
  Measured on this link, a 88 MB push already takes minutes.
* JPEG is already compressed, so git's delta encoding buys nothing -- every
  re-export stores a fresh full-size copy and ``.git`` only grows.
* It breaks the git-connected Cloudflare build. The 2026-09-17 Workers deploy
  died on a single ``.git`` packfile of 82.6 MiB; the cap is 25 MiB per file,
  and originals in history push that packfile into the GB range permanently.

So this repo carries WebP derivatives instead, one pair per original:

    thumb   max width  800 px, quality 74   grids, tiles, collage
    large   max width 2560 px, quality 82   lightbox / full screen

2560 px is deliberate, not a compromise. It covers a 2560-wide viewport at 1:1
-- every laptop, tablet and phone at full screen -- which is the tier a
photography site is expected to serve. Measured across six originals drawn from
both topics and projects, the lightbox tier lands near 590 KB against roughly
6 MB for the source JPEG, and no screen in common use can show more detail than
it carries.

Neither size is ever upscaled: a source narrower than the target is re-encoded
at its own width. EXIF is dropped on purpose -- the readable camera metadata
already lives in ``photo-data.js``, so keeping the binary block would only bloat
files and leak shooting locations.

``photo-data.js`` keeps ``master`` pointing at the original path as provenance.
No page loads it: ``xian-map.js`` and ``portfolio-page.js`` read ``thumb`` and
``large`` only. ``master`` exists so a photo can be traced back to the archived
original in the local deploy folder.

Usage
-----
    python scripts/build_webp_variants.py --report     # inspect, write nothing
    python scripts/build_webp_variants.py --write      # generate + rewrite data
    python scripts/build_webp_variants.py --data-only  # rewrite data file only
    python scripts/build_webp_variants.py --write --force  # ignore the cache

Changing VARIANTS is enough to trigger a re-encode: a derivative counts as
current only when its width matches the recipe, so raising a width rebuilds the
tier on the next run. ``--force`` is for re-encoding at the *same* settings.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
# The deploy folder sits beside the _work directory that holds this repo.
# Override with --source when the originals live somewhere else.
DEFAULT_SOURCE = ROOT.parent.parent / "cloudflare-deploy"
OPT_REL = Path("assets") / "opt"
DATA_FILE = ROOT / "photo-data.js"
LIBRARY_PREFIX = "window.PHOTO_LIBRARY ="
BANNER = "/* Generated by scripts/build_webp_variants.py -- do not edit by hand. */"

# (name, max width in px, webp quality). The thumb width matches the pair the
# site was built against so grid framing does not shift; `large` was raised to
# 2560 once this repo became the published tree, because it is now the only
# copy of the photo a visitor ever receives.
#
# Changing a width or quality rewrites the *same* file names with new bytes.
# `/assets/opt/*` is cached for 30 days without `immutable` for exactly that
# reason -- see `_headers`. If a re-encode has to land sooner than the cache
# window, put the spec in the name here (`large2560`) so the URL changes too.
VARIANTS = (("thumb", 800, 74), ("large", 2560, 82))
WEBP_METHOD = 5  # 0-6, higher is slower but produces smaller files
JPEG_SUFFIXES = (".jpg", ".jpeg", ".JPG", ".JPEG")

# Code files that name an image directly instead of going through
# photo-data.js. A hard-coded original path would 404 in this repo -- e.g.
# styles.css paints the page header with
# `url("assets/opt/topics/城市脉动/_DSC4018.jpg")`. Those references are
# rewritten to the `large` derivative.
#
# photo-data.js is excluded on purpose: its `master` field is a provenance
# record, not a URL. So is hero-sets.js's `source` field. Both are meant to
# name the original that the deploy folder serves.
CODE_FILES = (
    "index.html",
    "portfolio.html",
    "xian-city-wall-map.html",
    "script.js",
    "portfolio-page.js",
    "xian-map.js",
    "styles.css",
)
ORIGINAL_REF = re.compile(r"assets/opt/[^\"'\s)]+\.jpe?g", re.IGNORECASE)

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


def human(n: float) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if abs(n) < 1024 or unit == "GB":
            return f"{n:.1f} {unit}" if unit != "B" else f"{n:.0f} B"
        n /= 1024
    return f"{n:.1f} GB"


def variant_path(original: str, name: str) -> str:
    """assets/opt/topics/自然风光/_DSC0095.jpg -> .../_DSC0095-thumb.webp"""
    p = Path(original)
    return (p.parent / f"{p.stem}-{name}.webp").as_posix()


def collect_sources(source_opt: Path) -> list[Path]:
    if not source_opt.is_dir():
        sys.exit(f"original image directory not found: {source_opt}")
    found = [
        path.relative_to(source_opt)
        for path in source_opt.rglob("*")
        if path.is_file() and path.suffix in JPEG_SUFFIXES
    ]
    return sorted(found)


def derivative_is_current(target: Path, src: Path, max_width: int) -> bool:
    """True when ``target`` already holds what this recipe asks for.

    Existence and mtime alone are not enough. A derivative is written after its
    source, so it is always "newer" -- meaning a change to VARIANTS would be
    silently ignored and the old resolution would survive forever. Comparing
    the rendered width catches that; it is a header read, not a decode.
    """
    if not target.exists():
        return False
    if target.stat().st_mtime < src.stat().st_mtime:
        return False
    try:
        with Image.open(target) as rendered:
            got = rendered.width
        with Image.open(src) as original:
            want = min(original.width, max_width)
    except Exception:
        # Unreadable or truncated: rebuild it rather than trust it.
        return False
    return got == want


def render(source_opt: str, rel: str, force: bool = False) -> tuple[str, dict, bool]:
    """Render both derivatives for one original."""
    src = Path(source_opt) / rel
    out_base = ROOT / OPT_REL / rel

    sizes: dict[str, int] = {}
    changed = False
    for name, max_width, quality in VARIANTS:
        target = out_base.parent / f"{out_base.stem}-{name}.webp"
        if not force and derivative_is_current(target, src, max_width):
            sizes[name] = target.stat().st_size
            continue

        target.parent.mkdir(parents=True, exist_ok=True)
        with Image.open(src) as image:
            # draft() lets libjpeg decode at reduced scale: a large speed win.
            image.draft("RGB", (max_width, max_width))
            image = ImageOps.exif_transpose(image)
            if image.mode not in ("RGB", "L"):
                image = image.convert("RGB")
            if image.width > max_width:
                image = image.resize(
                    (max_width, round(image.height * max_width / image.width)),
                    Image.LANCZOS,
                )
            # No exif= argument -> metadata is dropped on purpose.
            image.save(target, "WEBP", quality=quality, method=WEBP_METHOD)
        sizes[name] = target.stat().st_size
        changed = True

    return rel, sizes, changed


def load_source_library(source_dir: Path) -> tuple[str, dict, str]:
    src_file = source_dir / "photo-data.js"
    if not src_file.is_file():
        sys.exit(f"data file not found: {src_file}")
    raw = src_file.read_text(encoding="utf-8-sig")
    i, j = raw.find("{"), raw.rfind("}")
    if i == -1 or j == -1:
        sys.exit(f"unexpected format in {src_file}")
    return raw[:i], json.loads(raw[i : j + 1]), raw[j + 1 :]


def iter_photos(library: dict):
    for topic in library.get("topics", {}).values():
        yield from topic.get("photos", [])
    for project in library.get("projects", {}).values():
        yield from project.get("photos", [])


def patch_library(library: dict) -> tuple[int, int]:
    """Point thumb/large at the derivatives; keep master as provenance."""
    patched = skipped = 0
    for photo in iter_photos(library):
        # In the deploy data file all three fields name the same original, so
        # whichever is present is the source of truth for the path.
        original = photo.get("master") or photo.get("thumb") or photo.get("large")
        if not original or not original.startswith("assets/opt/"):
            skipped += 1
            continue
        photo["master"] = original
        for name, _, _ in VARIANTS:
            photo[name] = variant_path(original, name)
        patched += 1

    for project in library.get("projects", {}).values():
        cover = project.get("cover")
        if isinstance(cover, str) and cover.startswith("assets/opt/"):
            project["cover"] = variant_path(cover, "large")

    return patched, skipped


def write_library(library: dict) -> int:
    library["generatedAt"] = time.strftime("%Y-%m-%d %H:%M:%S")
    body = json.dumps(library, ensure_ascii=False, indent=2)
    out = f"{BANNER}\n{LIBRARY_PREFIX} {body};\n"
    DATA_FILE.write_text(out, encoding="utf-8", newline="")
    return len(out)


def rewrite_code_refs() -> list[tuple[str, int]]:
    """Repoint hard-coded image URLs in code at the `large` derivative."""
    changed: list[tuple[str, int]] = []
    for name in CODE_FILES:
        path = ROOT / name
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")

        def repl(match: re.Match) -> str:
            target = variant_path(match.group(0), "large")
            # Leave it untouched when the derivative is missing: a broken
            # reference is easier to spot than a silently dropped one.
            return target if (ROOT / target).exists() else match.group(0)

        new = ORIGINAL_REF.sub(repl, text)
        if new != text:
            path.write_text(new, encoding="utf-8", newline="")
            changed.append((name, len(ORIGINAL_REF.findall(text))))
    return changed


def verify(library: dict, sources: list[Path]) -> int:
    problems: list[str] = []
    sizes: list[tuple[int, str]] = []
    total = 0
    count = 0
    used: set[str] = set()

    for photo in iter_photos(library):
        for name, _, _ in VARIANTS:
            value = photo.get(name)
            if not value:
                problems.append(f"{photo.get('id')}: missing {name}")
                continue
            if not value.endswith(f"-{name}.webp"):
                problems.append(f"{photo.get('id')}: {name} is not a derivative ({value})")
                continue
            path = ROOT / value
            if not path.exists():
                problems.append(f"{photo.get('id')}: {name} file not found ({value})")
                continue
            size = path.stat().st_size
            sizes.append((size, value))
            used.add(value)
            total += size
            count += 1

    for project in library.get("projects", {}).values():
        cover = project.get("cover")
        if cover and not (ROOT / cover).exists():
            problems.append(f"{project.get('id')}: cover file not found ({cover})")

    # No code file may still name an original: this repo does not ship them,
    # so any leftover reference is a guaranteed 404 once the page runs.
    leftovers: list[tuple[str, str]] = []
    for name in CODE_FILES:
        path = ROOT / name
        if not path.is_file():
            continue
        for ref in sorted(set(ORIGINAL_REF.findall(path.read_text(encoding="utf-8")))):
            leftovers.append((name, ref))
    if leftovers:
        print(f"\n{len(leftovers)} hard-coded original reference(s) still in code:")
        for name, ref in leftovers[:10]:
            print(f"    {name}: {ref}")
        problems.append(f"{len(leftovers)} code reference(s) still name an original")

    # Any derivative on disk that no entry references is dead weight in git.
    on_disk = {
        p.relative_to(ROOT).as_posix() for p in (ROOT / OPT_REL).rglob("*.webp")
    }
    orphans = sorted(on_disk - used)

    photos = list(iter_photos(library))
    print(f"originals on disk : {len(sources)}")
    print(f"photos referenced : {len(photos)}")
    print(f"derivative files  : {count} ({len(used)} distinct)")
    print(f"repo image size   : {human(total)}")
    if sizes:
        sizes.sort(reverse=True)
        print(f"largest file      : {sizes[0][1]} ({human(sizes[0][0])})")

    if orphans:
        print(f"\n{len(orphans)} derivative(s) on disk but not referenced:")
        for item in orphans[:15]:
            print("   ", item)
        problems.append(f"{len(orphans)} unreferenced derivative file(s)")

    if problems:
        print(f"\n{len(problems)} problem(s):")
        for item in problems[:30]:
            print("  -", item)
        return 1

    print("\nOK every entry has a servable thumb and large; no orphan files")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--source",
        default=str(DEFAULT_SOURCE),
        help="folder holding the originals under assets/opt/ (default: the deploy folder)",
    )
    ap.add_argument("--report", action="store_true", help="inspect only, write nothing")
    ap.add_argument("--write", action="store_true", help="generate derivatives and rewrite data")
    ap.add_argument("--data-only", action="store_true", help="skip image generation")
    ap.add_argument(
        "--force",
        action="store_true",
        help="re-encode every derivative even when it already matches VARIANTS",
    )
    ap.add_argument("--jobs", type=int, default=min(8, os.cpu_count() or 4))
    args = ap.parse_args()

    source_dir = Path(args.source).resolve()
    source_opt = source_dir / OPT_REL
    sources = collect_sources(source_opt)
    print(f"source            : {source_opt}")
    print(f"originals found   : {len(sources)}")

    _, library, _ = load_source_library(source_dir)

    if not args.write:
        pending = []
        for rel in sources:
            base = (ROOT / OPT_REL / rel).parent
            stem = (ROOT / OPT_REL / rel).stem
            if not all(
                derivative_is_current(
                    base / f"{stem}-{name}.webp", source_opt / rel, max_width
                )
                for name, max_width, _ in VARIANTS
            ):
                pending.append(rel)
        print(f"derivatives ready : {len(sources) - len(pending)} / {len(sources)}")
        for rel in pending[:5]:
            print(f"  stale           : {rel}")
        patched, skipped = patch_library(library)
        print(f"would rebind      : {patched} entries ({skipped} skipped)")
        print("\n[dry run] nothing written. Add --write to apply.")
        return 0

    source_bytes = sum((source_opt / rel).stat().st_size for rel in sources)

    if not args.data_only:
        started = time.time()
        changed = 0
        with ProcessPoolExecutor(max_workers=args.jobs) as pool:
            futures = [
                pool.submit(render, str(source_opt), str(rel), args.force)
                for rel in sources
            ]
            for done, future in enumerate(as_completed(futures), start=1):
                _, _, did_change = future.result()
                changed += 1 if did_change else 0
                if done % 25 == 0 or done == len(sources):
                    print(
                        f"  [{done}/{len(sources)}] {time.time() - started:6.1f}s  "
                        f"rebuilt {changed}",
                        flush=True,
                    )
        print(f"rendered {len(sources)} originals ({human(source_bytes)} in, {changed} rebuilt)")

    patched, skipped = patch_library(library)
    nbytes = write_library(library)
    print(f"photo-data.js rewritten: {patched} entries bound to WebP, {skipped} skipped "
          f"({nbytes} bytes)")

    for name, n in rewrite_code_refs():
        print(f"repointed {n} hard-coded original reference(s) in {name}")

    return verify(library, sources)


if __name__ == "__main__":
    sys.exit(main())
